language: java
jdk: openjdk6
branches:
  only: command
env:
  global:
  - GTFS_URL="http://data.keolis-rennes.com/fileadmin/OpenDataFiles/GTFS/GTFS-20131031.zip"
  - secure: "B+46iFiWaZAw92r5sN4fyRVPNeJhtiPjEUTbMmFKf/eMUIELXCnZfnezZzeZq4XtmroUbuCMh0kM42G101X3HLzcTCzQ2q0FiDIX5h6zFWPidHRlB24dEd1HC9qPWC9eCUGY/s1cXgd1v7GR1zFOulxo7/UX41Jen0t36fTmVR0="
  - secure: "K1W2JHG2uIhRGc9Kr5OjfCyA6DFflrZkj45yMoc8NuFoMMNyS8Z9or69Zi6J6z+q8QYmZzcq3c6mSNaiK/BHMulqIWfRoOAbKSg/S/3ZhaDMSwKbHDWjvAumw62vtdj9PK7woBtaaX+Y63Bwd70i1tmAp1V6gvkt2Oq7TGfWPxk="

before_script:
# setup git
- git config --global user.email "jeremie+travis+itinerennes+data+bundle+generator@dudie.fr"
- git config --global user.name "Travis CI"

# install Travis tools
- git clone https://gist.github.com/7630453.git travis-tools

# register Github identity
- curl "https://raw.github.com/dudie/maven-repository/master/github_key.pub" >> ~/.ssh/known_hosts
#- cat travis-tools/id_github.pub > ~/.ssh/known_hosts
- cat ~/.ssh/known_hosts

# setup private key for deployment
- cat id_itinerennes-data-bundle-generator.enc | ./travis-tools/decrypt.sh $KEY > id_itinerennes-data-bundle-generator
- chmod 400 id_itinerennes-data-bundle-generator
- eval $(ssh-agent)
- ssh-add id_itinerennes-data-bundle-generator

# export GTFS file identifier
- export GTFS_ID=$(basename $GTFS_URL)

# download GTFS data bundle
- wget $GTFS_URL -O GTFS.zip

# download itinerennes data bundle generator
- wget "https://raw.github.com/dudie/maven-repository/snapshots/fr/itinerennes/itinerennes-data-bundle-generator/1.0-SNAPSHOT/itinerennes-data-bundle-generator-1.0-20131126.231151-1-dist-pkg.tar.bz2" -O itinerennes-data-bundle-generator.tar.bz2
- tar jxf itinerennes-data-bundle-generator.tar.bz2

# clone itinerennes-api repository
- git clone git@github.com:dudie/itinerennes-api.git
- cd itinerennes-api
- git checkout data
- cd -

script:
- ./itinerennes-data-bundle-generator/bundler.sh GTFS.zip -am 1=2 -k $KEOLIS_API_KEY -o itinerennes-api
- cd itinerennes-api
- git add .
- git commit -m "Add data from $GTFS_ID" | grep -v "^ create mode"
- git push origin data

